<?php
namespace EIS\Lab\SIF;

$pages = [
       1 => ['game'=>0],
       2 => ['key'=>'calendar/login', 'title'=>'SIF 特殊登录奖励', 'game'=>1, 'path'=>'calendar/login'],
       3 => ['key'=>'list/steps', 'title'=>'SIF 阶梯单级', 'game'=>1, 'path'=>'list/steps'],
       4 => ['key'=>'history', 'title'=>'更新记录', 'game'=>0, 'path'=>'history'],
       5 => ['key'=>'article'],
       6 => ['key'=>'event/mf', 'title'=>'Medley Festival 任务一览', 'game'=>1, 'path'=>'list/mf-missions'],
       7 => ['key'=>'calendar/login', 'title'=>'SIFAS 特殊登录奖励', 'game'=>2, 'path'=>'calendar/login'],
       8 => ['key'=>'list/stories', 'title'=>'SIF 特别剧情', 'game'=>1, 'path'=>'list/stories'],
       9 => ['key'=>'list/stepups', 'title'=>'SIF 阶梯招募', 'game'=>1, 'path'=>'list/stepups'],
      10 => ['key'=>'list/trades', 'title'=>'SIF 活动交换所', 'game'=>1, 'path'=>'list/trades'],
      11 => ['key'=>'list/trades', 'title'=>'SIFAS 活动交换所', 'game'=>2, 'path'=>'list/trades'],
      12 => ['title'=>'维护中', 'game'=>0, 'path'=>'maintenance'],
      13 => ['key'=>'list/carnivals', 'title'=>'节奏嘉年华活动歌单', 'game'=>1, 'path'=>'list/carnivals'],
      14 => ['key'=>'list/goals', 'title'=>'部分限时课题文本', 'game'=>1, 'path'=>'list/goals'],
      15 => ['key'=>'list/voices', 'title'=>'SIFAS 语音文本', 'game'=>2, 'path'=>'list/voices'],
      16 => ['key'=>'gallery/covers', 'title'=>'封面背景图库', 'game'=>1, 'path'=>'gallery/covers'],
      17 => ['key'=>'sim/boxes', 'title'=>'SIF 招募模拟', 'game'=>1, 'path'=>'sim/boxes'],
      18 => ['key'=>'latest/event', 'title'=>'SIF 最新活动资讯', 'game'=>1, 'path'=>'latest/event'],
      19 => ['key'=>'gallery/posters', 'title'=>'招募画像图库', 'game'=>1, 'path'=>'gallery/posters'],
      20 => ['key'=>'detail/lives', 'title'=>'SIFAS 歌曲综合资料', 'game'=>2, 'path'=>'detail/lives'],
      21 => ['key'=>'tool/event', 'title'=>'活动 pt 计算器', 'game'=>1, 'path'=>'tool/event'],
      22 => ['key'=>'event/arena', 'title'=>'Live ♪ Arena 活动资讯', 'game'=>1, 'path'=>'latest/arena'],
      23 => ['key'=>'list/goals', 'title'=>'SIFAS 活动课题', 'game'=>2, 'path'=>'list/goals'],
      24 => ['key'=>'archive/notices', 'title'=>'过去的告知', 'game'=>0, 'path'=>'archive/notices'],
      25 => ['key'=>'play/richman', 'game'=>1, 'path'=>'sim/richman'],
      26 => ['key'=>'play/aquarium', 'game'=>1, 'path'=>'sim/aquarium'],
      27 => ['key'=>'tool/accessories', 'title'=>'SIF 饰品计算器', 'game'=>1, 'path'=>'tool/accessories'],
      28 => ['key'=>'sim/gacha', 'title'=>'SIF 招募模拟', 'game'=>1, 'path'=>'sim/gacha'],
      29 => ['key'=>'list/accessories', 'title'=>'SIF 饰品一览', 'game'=>1, 'path'=>'list/accessories'],
      30 => ['key'=>'play/mattribux', 'game'=>0, 'path'=>'play/mattribux'],
      31 => ['key'=>'museum/arena', 'title'=>'Live ♪ Arena 剧情合集', 'game'=>1, 'path'=>'migrate/arena'],
      32 => ['key'=>'museum/yell', 'title'=>'SIF 活动加成一览', 'game'=>1, 'path'=>'list/event-cheers'],
];
